cache:
  - packages -> **\packages.config
nuget:
  project_feed: true
  disable_publish_on_pr: true
configuration:
  - Release

before_build:
  - nuget restore

build:
  project: Library.sln
  publish_nuget: true
  publish_nuget_symbols: true
  
deploy:
- provider: NuGet
  api_key:
    secure: iZwnbScYpfsmtejUkrw8YGsB3pFzRnphKd+oVYCZ/A2J4diRYIjJc9ZH1SifkeAk
  skip_symbols: false
  
notifications:
- provider: Slack
  auth_token:
    secure: JD81X3zvuMSlPRSKi5RVkSF8XIcjfskQA5cXUjZxP0wQEWvoczzoHA95AB3nugWo9hfDet+aTlBOgLqMOcEsyg==
  channel: '#developers'
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
